### ISSUE TITLE
GPU memory required to train 8x8 patch Models

### ISSUE THREAD

**Issue by gokberkgul** [facebookresearch/dino#104]
Hi,

I am training on a custom dataset where all images are 224x224 with 4 A100 GPU's. Everytime I want to train 8x8 models, I get the following error for each GPU (only pasted for GPU 0)

```
Traceback (most recent call last):
  File "/home/ag23peby/dino/main_dino.py", line 472, in <module>
    train_dino(args)
  File "/home/ag23peby/dino/main_dino.py", line 276, in train_dino
    epoch, fp16_scaler, args)
  File "/home/ag23peby/dino/main_dino.py", line 320, in train_one_epoch
    student_output = student(images)
  File "/home/ag23peby/.env/lib64/python3.6/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ag23peby/.env/lib64/python3.6/site-packages/torch/nn/parallel/distributed.py", line 799, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "/home/ag23peby/.env/lib64/python3.6/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/work/home/ag23peby/dino/utils.py", line 602, in forward
    _out = self.backbone(torch.cat(x[start_idx: end_idx]))
  File "/home/ag23peby/.env/lib64/python3.6/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/work/home/ag23peby/dino/vision_transformer.py", line 212, in forward
    y = blk(y)
  File "/home/ag23peby/.env/lib64/python3.6/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/work/home/ag23peby/dino/vision_transformer.py", line 108, in forward
    y, attn = self.attn(self.norm1(x))
  File "/home/ag23peby/.env/lib64/python3.6/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/work/home/ag23peby/dino/vision_transformer.py", line 85, in forward
    attn = (q @ k.transpose(-2, -1)) * self.scale
RuntimeError: CUDA out of memory. Tried to allocate 904.00 MiB (GPU 0; 39.59 GiB total capacity; 37.17 GiB already allocated; 270.19 MiB free; 37.46 GiB reserved in total by PyTorch)
```
The configuration I use is

```
srun /home/ag23peby/.env/bin/python -m torch.distributed.launch --nproc_per_node=4 /home/ag23peby/dino/main_dino.py --arch vit_small \
    --epochs 4 --data_path /work/scratch/ag23peby/processed/mag20 --num_workers 8 --batch_size_per_gpu 64 \
    --warmup_epochs 0 --patch_size 8 --local_crops_number 4
```

Even when I am training vit_base model with 16x16 patches, the GPU usage is
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  A100-PCIE-40GB      On   | 00000000:99:00.0 Off |                    0 |
| N/A   84C    P0   211W / 250W |  25806MiB / 40536MiB |    100%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
|   1  A100-PCIE-40GB      On   | 00000000:AD:00.0 Off |                    0 |
| N/A   85C    P0    88W / 250W |  25806MiB / 40536MiB |    100%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
|   2  A100-PCIE-40GB      On   | 00000000:C5:00.0 Off |                    0 |
| N/A   84C    P0   152W / 250W |  25808MiB / 40536MiB |    100%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
|   3  A100-PCIE-40GB      On   | 00000000:D9:00.0 Off |                    0 |
| N/A   84C    P0    89W / 250W |  25808MiB / 40536MiB |    100%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A   2960439      C   .../ag23peby/.env/bin/python    25801MiB |
|    1   N/A  N/A   2960440      C   .../ag23peby/.env/bin/python    25799MiB |
|    2   N/A  N/A   2960441      C   .../ag23peby/.env/bin/python    25801MiB |
|    3   N/A  N/A   2960442      C   .../ag23peby/.env/bin/python    25801MiB |
+-----------------------------------------------------------------------------+
```

which 25GB memory per GPU feels like too much. Am I doing something wrong? I would assume A100 GPU would handle 64 batch size with 4 local crops.

**Comment by mathildecaron31** [comment]
Hello @gokberkgul 

Thanks for your interest in this work.

I recommend that you take a look at the list of arguments used for the training of the different models: https://dl.fbaipublicfiles.com/dino/dino_deitsmall8_pretrain/args.txt for example.

I trained the ViT-S/8 model with ``--batch_size_per_gpu 16`` on 64 V100-32Gb GPUs.

Also I would recommend to switch off mixed precision training with the 8x8 models since we observed that it leads to instability in training.

Overall for vit-s/8, can you try with ``--batch_size_per_gpu 20 --use_fp16 false`` ?

**Comment by gokberkgul** [comment]
![image](https://user-images.githubusercontent.com/48859147/129340742-a6540ffe-b3ce-4cbe-9b9e-aa05ef6727df.png)
Thanks. I thought you used the same configuration for s/8 and s/16. I only have access to 4 GPUs, Would you think training ViT-B/16 with batch size of 256 perform better than ViT-S/8 with a batch size of 64? I am taking your ImageNet pre-trained weights and fine-tuning them over a medical dataset. Thank you for the great work by the way.

**Comment by mathildecaron31** [comment]
Hi, it's difficult to say without running the experiments... In any case, when running models with small batch sizes I would recommend to increase the momentum parameter (0.9995 instead of 0.996).

**Comment by mathildecaron31** [comment]
Closing the issue. Feel free to re-open @gokberkgul if needed

**Comment by jafarinia** [comment]
Hi
I want to know what do you mean by "small"? (can you specify a range pls?)
