### ISSUE TITLE
Issue with `dino_resnet50`

### ISSUE THREAD

**Issue by tchaton** [facebookresearch/dino#11]
>>> torch.hub.load('facebookresearch/dino:main', 'dino_resnet50')
Using cache found in /Users/thomas/.cache/torch/hub/facebookresearch_dino_main
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/thomas/Documents/GitHub/lightning-flash/.venv/lib/python3.7/site-packages/torch/hub.py", line 339, in load
    model = _load_local(repo_or_dir, model, *args, **kwargs)
  File "/Users/thomas/Documents/GitHub/lightning-flash/.venv/lib/python3.7/site-packages/torch/hub.py", line 368, in _load_local
    model = entry(*args, **kwargs)
  File "/Users/thomas/.cache/torch/hub/facebookresearch_dino_main/hubconf.py", line 82, in dino_resnet50
    model.load_state_dict(state_dict, strict=True)
  File "/Users/thomas/Documents/GitHub/lightning-flash/.venv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1224, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for ResNet:
        Missing key(s) in state_dict: "fc.weight", "fc.bias".

**Comment by mathildecaron31** [comment]
Hi @tchaton 

Thanks for raising this issue. It should work know.

https://github.com/facebookresearch/dino/commit/1d06521adfc53c80dece1a74902f718873e9821d
