### ISSUE TITLE
OSERROR Errno5 Input/output error when reading files

### ISSUE THREAD

**Issue by Lost2Dream** [facebookresearch/dino#155]
```
Using cache found in /root/.cache/torch/hub/facebookresearch_xcit_main
Will run the code on one GPU.
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
git:
  sha: N/A, status: clean, branch: N/A

addr: 10.136.181.115
amp: False
arch: resnet50
batch_size_per_gpu: 8
clip_grad: 3.0
data_path: /opt/npu/imagenet/train/
device: npu
device_list: 0
dist_url: env://
drop_path_rate: 0.1
epochs: 100
freeze_last_layer: 1
global_crops_scale: [0.14, 1.0]
gpu: 0
local_crops_number: 8
local_crops_scale: [0.05, 0.14]
local_rank: 0
loss_scale: 1024.0
lr: 0.03
min_lr: 1e-06
momentum_teacher: 0.996
norm_last_layer: True
num_workers: 1
opt_level: O2
optimizer: sgd
out_dim: 65536
output_dir: ../output
patch_size: 16
process_device_map: {0: 0}
rank: 0
saveckp_freq: 20
seed: 0
teacher_temp: 0.04
use_bn_in_head: False
use_fp16: False
warmup_epochs: 10
warmup_teacher_temp: 0.04
warmup_teacher_temp_epochs: 0
weight_decay: 0.0001
weight_decay_end: 0.0001
world_size: 1
Data loaded: there are 1281167 images.
Using cache found in /root/.cache/torch/hub/facebookresearch_xcit_main
Student and Teacher are built: they are both resnet50 network.
Loss, optimizer and schedulers ready.
Starting DINO training !
Epoch: [0/100]  [     0/160145]  eta: 510 days, 13:31:14  loss: 10.439739 (10.439739)  lr: 0.000000 (0.000000)  wd: 0.000100 (0.000100)  time: 275.454590  data: 0.496930  max mem: 3393
Traceback (most recent call last):
  File "/home/DINO/main/main_dino.py", line 608, in <module>
    train_dino(args)
  File "/home/DINO/main/main_dino.py", line 302, in train_dino
    epoch, fp16_scaler, args)
  File "/home/DINO/main/main_dino.py", line 339, in train_one_epoch
    for it, (images, _) in enumerate(metric_logger.log_every(data_loader, 10, header)):
  File "/home/DINO/main/utils.py", line 382, in log_every
    for obj in iterable:
  File "/root/anaconda3/envs/CenterNet/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 362, in __next__
    data = self._next_data()
  File "/root/anaconda3/envs/CenterNet/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 878, in _next_data
    return self._process_data(data)
  File "/root/anaconda3/envs/CenterNet/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 903, in _process_data
    data.reraise()
  File "/root/anaconda3/envs/CenterNet/lib/python3.7/site-packages/torch/_utils.py", line 416, in reraise
    raise self.exc_type(msg)
OSError: Caught OSError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/root/anaconda3/envs/CenterNet/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/root/anaconda3/envs/CenterNet/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/root/anaconda3/envs/CenterNet/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/root/anaconda3/envs/CenterNet/lib/python3.7/site-packages/torchvision/datasets/folder.py", line 135, in __getitem__
    sample = self.loader(path)
  File "/root/anaconda3/envs/CenterNet/lib/python3.7/site-packages/torchvision/datasets/folder.py", line 171, in default_loader
    return pil_loader(path)
  File "/root/anaconda3/envs/CenterNet/lib/python3.7/site-packages/torchvision/datasets/folder.py", line 154, in pil_loader
    return img.convert('RGB')
  File "/root/anaconda3/envs/CenterNet/lib/python3.7/site-packages/PIL/Image.py", line 915, in convert
    self.load()
  File "/root/anaconda3/envs/CenterNet/lib/python3.7/site-packages/PIL/ImageFile.py", line 237, in load
    s = read(self.decodermaxblock)
  File "/root/anaconda3/envs/CenterNet/lib/python3.7/site-packages/PIL/JpegImagePlugin.py", line 402, in load_read
    s = self.fp.read(read_bytes)
OSError: [Errno 5] Input/output error
```
These displayed after training one step in epoch0
I need help, thanks

**Comment by Lost2Dream** [comment]
```
nohup python -u /home/DINO/main/main_dino.py --device-list 0 --arch resnet50 --batch_size_per_gpu 4 --optimizer sgd --lr 0.03 --weight_decay 
1e-4 --weight_decay_end 1e-4 --global_crops_scale 0.14 1 --local_crops_scale 0.05 0.14 --data_path /opt/npu/imagenet/train/ --output_dir ../output
~      
```
this is my running shell

**Comment by woctezuma** [comment]
Make sure your images are not corrupted, and that they can be read.

References among many others:
- https://github.com/facebookresearch/detectron2/issues/764
- https://stackoverflow.com/a/62550189/376454

**Comment by Lost2Dream** [comment]
I have seen this Issue#764 before, and I try to set dataloader worker num = 1, and my imagenet is origin, no change anything
but my code output something like this:
```
x:
{'shape': (32, 8, 24, 24, 16), 'ori_shape': (32, 128, 24, 24), 'format': 'NC1HWC0', 'sub_format': 0, 'ori_format': 'NCHW', 'dtype': 'float32', 'addr_type': 0, 'valid_shape': (), 'slice_offset': (), 'sgt_slice_shape': (), 'L1_workspace_size': -1, 'L1_fusion_type': -1, 'L1_addr_offset': 0, 'total_shape': [32, 8, 24, 24, 16], 'split_index': 0, 'param_name': 'x'}
{'shape': (1, 8, 1, 1, 16), 'ori_shape': (128,), 'format': 'NC1HWC0', 'sub_format': 0, 'ori_format': 'NCHW', 'dtype': 'float32', 'addr_type': 0, 'valid_shape': (), 'slice_offset': (), 'sgt_slice_shape': (), 'L1_workspace_size': -1, 'L1_fusion_type': -1, 'L1_addr_offset': 0, 'total_shape': [1, 8, 1, 1, 16], 'split_index': 0, 'param_name': 'sum'}
x:
{'shape': (32, 128, 3, 3, 16), 'ori_shape': (32, 2048, 3, 3), 'format': 'NC1HWC0', 'sub_format': 0, 'ori_format': 'NCHW', 'dtype': 'float32', 'addr_type': 0, 'valid_shape': (), 'slice_offset': (), 'sgt_slice_shape': (), 'L1_workspace_size': -1, 'L1_fusion_type': -1, 'L1_addr_offset': 0, 'total_shape': [32, 128, 3, 3, 16], 'split_index': 0, 'param_name': 'x'}
{'shape': (1, 128, 1, 1, 16), 'ori_shape': (2048,), 'format': 'NC1HWC0', 'sub_format': 0, 'ori_format': 'NCHW', 'dtype': 'float32', 'addr_type': 0, 'valid_shape': (), 'slice_offset': (), 'sgt_slice_shape': (), 'L1_workspace_size': -1, 'L1_fusion_type': -1, 'L1_addr_offset': 0, 'total_shape': [1, 128, 1, 1, 16], 'split_index': 0, 'param_name': 'sum'}
```
