### ISSUE TITLE
Training on the custom dataset. Potentially failing to parse facebookresearch/xcit 

### ISSUE THREAD

**Issue by Instassa** [facebookresearch/dino#159]
Huge thank you to the authors for sharing their code with the comunity.

I have the following issue when trying to train DINO on the custom dataset, i.e. `python -m torch.distributed.launch --nproc_per_node=8 main_dino.py --arch vit_small --data_path ../pre-process/step2_affine_transformation/LRS3_fullface13_correct_mp4 --output_dir /LRS3_dino_pretext/`

I am not sure whether this is caused by something on my end, however it looks like something breaks when trying to reach facebookresearch/xcit in line 47 of main_dino.py. 

Would you be so kind to help me with some advice on how to fix this?

    *****************************************
    Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
    *****************************************
    Downloading: "https://github.com/facebookresearch/xcit/archive/master.zip" to /data/home/marijajegorova/.cache/torch/hub/master.zip
    Downloading: "https://github.com/facebookresearch/xcit/archive/master.zip" to /data/home/marijajegorova/.cache/torch/hub/master.zip
    Downloading: "https://github.com/facebookresearch/xcit/archive/master.zip" to /data/home/marijajegorova/.cache/torch/hub/master.zip
    Downloading: "https://github.com/facebookresearch/xcit/archive/master.zip" to /data/home/marijajegorova/.cache/torch/hub/master.zip
    Downloading: "https://github.com/facebookresearch/xcit/archive/master.zip" to /data/home/marijajegorova/.cache/torch/hub/master.zip
    Downloading: "https://github.com/facebookresearch/xcit/archive/master.zip" to /data/home/marijajegorova/.cache/torch/hub/master.zip
    Downloading: "https://github.com/facebookresearch/xcit/archive/master.zip" to /data/home/marijajegorova/.cache/torch/hub/master.zip
    Downloading: "https://github.com/facebookresearch/xcit/archive/master.zip" to /data/home/marijajegorova/.cache/torch/hub/master.zip
    Traceback (most recent call last):
    Traceback (most recent call last):
    Traceback (most recent call last):
    Traceback (most recent call last):
    Traceback (most recent call last):
      File "main_dino.py", line 468, in <module>
      File "main_dino.py", line 468, in <module>
      File "main_dino.py", line 468, in <module>
      File "main_dino.py", line 468, in <module>
      File "main_dino.py", line 468, in <module>
    Traceback (most recent call last):
      File "main_dino.py", line 468, in <module>
    Traceback (most recent call last):
      File "main_dino.py", line 468, in <module>
    Traceback (most recent call last):
      File "main_dino.py", line 468, in <module>
        parser = argparse.ArgumentParser('DINO', parents=[get_args_parser()])
      File "main_dino.py", line 47, in get_args_parser
        parser = argparse.ArgumentParser('DINO', parents=[get_args_parser()])
      File "main_dino.py", line 47, in get_args_parser
        parser = argparse.ArgumentParser('DINO', parents=[get_args_parser()])
      File "main_dino.py", line 47, in get_args_parser
        parser = argparse.ArgumentParser('DINO', parents=[get_args_parser()])
      File "main_dino.py", line 47, in get_args_parser
        parser = argparse.ArgumentParser('DINO', parents=[get_args_parser()])
      File "main_dino.py", line 47, in get_args_parser
        + torchvision_archs + torch.hub.list("facebookresearch/xcit"),
      File "/data/home/marijajegorova/miniconda/envs/ae-p38/lib/python3.8/site-packages/torch/hub.py", line 238, in list
        + torchvision_archs + torch.hub.list("facebookresearch/xcit"),
      File "/data/home/marijajegorova/miniconda/envs/ae-p38/lib/python3.8/site-packages/torch/hub.py", line 238, in list
        repo_dir = _get_cache_or_reload(github, force_reload, True)
      File "/data/home/marijajegorova/miniconda/envs/ae-p38/lib/python3.8/site-packages/torch/hub.py", line 144, in _get_cache_or_reload
        download_url_to_file(url, cached_file, progress=False)
      File "/data/home/marijajegorova/miniconda/envs/ae-p38/lib/python3.8/site-packages/torch/hub.py", line 394, in download_url_to_file
        repo_dir = _get_cache_or_reload(github, force_reload, True)
      File "/data/home/marijajegorova/miniconda/envs/ae-p38/lib/python3.8/site-packages/torch/hub.py", line 144, in _get_cache_or_reload
        parser = argparse.ArgumentParser('DINO', parents=[get_args_parser()])
      File "main_dino.py", line 47, in get_args_parser
        parser = argparse.ArgumentParser('DINO', parents=[get_args_parser()])
      File "main_dino.py", line 47, in get_args_parser
        u = urlopen(req)
      File "/data/home/marijajegorova/miniconda/envs/ae-p38/lib/python3.8/urllib/request.py", line 222, in urlopen
        download_url_to_file(url, cached_file, progress=False)
      File "/data/home/marijajegorova/miniconda/envs/ae-p38/lib/python3.8/site-packages/torch/hub.py", line 394, in download_url_to_file
        + torchvision_archs + torch.hub.list("facebookresearch/xcit"),
      File "/data/home/marijajegorova/miniconda/envs/ae-p38/lib/python3.8/site-packages/torch/hub.py", line 238, in list
        u = urlopen(req)
      File "/data/home/marijajegorova/miniconda/envs/ae-p38/lib/python3.8/urllib/request.py", line 222, in urlopen
        + torchvision_archs + torch.hub.list("facebookresearch/xcit"),
      File "/data/home/marijajegorova/miniconda/envs/ae-p38/lib/python3.8/site-packages/torch/hub.py", line 238, in list
        return opener.open(url, data, timeout)
      File "/data/home/marijajegorova/miniconda/envs/ae-p38/lib/python3.8/urllib/request.py", line 531, in open
        return opener.open(url, data, timeout)
      File "/data/home/marijajegorova/miniconda/envs/ae-p38/lib/python3.8/urllib/request.py", line 531, in open
        repo_dir = _get_cache_or_reload(github, force_reload, True)
      File "/data/home/marijajegorova/miniconda/envs/ae-p38/lib/python3.8/site-packages/torch/hub.py", line 144, in _get_cache_or_reload
        repo_dir = _get_cache_or_reload(github, force_reload, True)
      File "/data/home/marijajegorova/miniconda/envs/ae-p38/lib/python3.8/site-packages/torch/hub.py", line 144, in _get_cache_or_reload
            response = meth(req, response)response = meth(req, response)
    
      File "/data/home/marijajegorova/miniconda/envs/ae-p38/lib/python3.8/urllib/request.py", line 640, in http_response
      File "/data/home/marijajegorova/miniconda/envs/ae-p38/lib/python3.8/urllib/request.py", line 640, in http_response
        download_url_to_file(url, cached_file, progress=False)
      File "/data/home/marijajegorova/miniconda/envs/ae-p38/lib/python3.8/site-packages/torch/hub.py", line 394, in download_url_to_file
        parser = argparse.ArgumentParser('DINO', parents=[get_args_parser()])
      File "main_dino.py", line 47, in get_args_parser
        download_url_to_file(url, cached_file, progress=False)
      File "/data/home/marijajegorova/miniconda/envs/ae-p38/lib/python3.8/site-packages/torch/hub.py", line 394, in download_url_to_file
        response = self.parent.error(
      File "/data/home/marijajegorova/miniconda/envs/ae-p38/lib/python3.8/urllib/request.py", line 563, in error
        response = self.parent.error(
      File "/data/home/marijajegorova/miniconda/envs/ae-p38/lib/python3.8/urllib/request.py", line 563, in error
        u = urlopen(req)
      File "/data/home/marijajegorova/miniconda/envs/ae-p38/lib/python3.8/urllib/request.py", line 222, in urlopen
        result = self._call_chain(*args)    
    u = urlopen(req)
      File "/data/home/marijajegorova/miniconda/envs/ae-p38/lib/python3.8/urllib/request.py", line 502, in _call_chain
      File "/data/home/marijajegorova/miniconda/envs/ae-p38/lib/python3.8/urllib/request.py", line 222, in urlopen
        result = self._call_chain(*args)
      File "/data/home/marijajegorova/miniconda/envs/ae-p38/lib/python3.8/urllib/request.py", line 502, in _call_chain
        return opener.open(url, data, timeout)
      File "/data/home/marijajegorova/miniconda/envs/ae-p38/lib/python3.8/urllib/request.py", line 531, in open
        return opener.open(url, data, timeout)
      File "/data/home/marijajegorova/miniconda/envs/ae-p38/lib/python3.8/urllib/request.py", line 531, in open
        result = func(*args)
      File "/data/home/marijajegorova/miniconda/envs/ae-p38/lib/python3.8/urllib/request.py", line 755, in http_error_302
        result = func(*args)
      File "/data/home/marijajegorova/miniconda/envs/ae-p38/lib/python3.8/urllib/request.py", line 755, in http_error_302
        response = meth(req, response)
      File "/data/home/marijajegorova/miniconda/envs/ae-p38/lib/python3.8/urllib/request.py", line 640, in http_response
        response = meth(req, response)
      File "/data/home/marijajegorova/miniconda/envs/ae-p38/lib/python3.8/urllib/request.py", line 640, in http_response
        return self.parent.open(new, timeout=req.timeout)
      File "/data/home/marijajegorova/miniconda/envs/ae-p38/lib/python3.8/urllib/request.py", line 531, in open
        response = self.parent.error(
      File "/data/home/marijajegorova/miniconda/envs/ae-p38/lib/python3.8/urllib/request.py", line 563, in error
        return self.parent.open(new, timeout=req.timeout)
      File "/data/home/marijajegorova/miniconda/envs/ae-p38/lib/python3.8/urllib/request.py", line 531, in open
        + torchvision_archs + torch.hub.list("facebookresearch/xcit"),
      File "/data/home/marijajegorova/miniconda/envs/ae-p38/lib/python3.8/site-packages/torch/hub.py", line 238, in list
        response = self.parent.error(
      File "/data/home/marijajegorova/miniconda/envs/ae-p38/lib/python3.8/urllib/request.py", line 563, in error
        response = meth(req, response)
      File "/data/home/marijajegorova/miniconda/envs/ae-p38/lib/python3.8/urllib/request.py", line 640, in http_response
        response = meth(req, response)
      File "/data/home/marijajegorova/miniconda/envs/ae-p38/lib/python3.8/urllib/request.py", line 640, in http_response
        result = self._call_chain(*args)
      File "/data/home/marijajegorova/miniconda/envs/ae-p38/lib/python3.8/urllib/request.py", line 502, in _call_chain
        repo_dir = _get_cache_or_reload(github, force_reload, True)
      File "/data/home/marijajegorova/miniconda/envs/ae-p38/lib/python3.8/site-packages/torch/hub.py", line 144, in _get_cache_or_reload
        result = self._call_chain(*args)
      File "/data/home/marijajegorova/miniconda/envs/ae-p38/lib/python3.8/urllib/request.py", line 502, in _call_chain
        response = self.parent.error(
      File "/data/home/marijajegorova/miniconda/envs/ae-p38/lib/python3.8/urllib/request.py", line 569, in error
        response = self.parent.error(
      File "/data/home/marijajegorova/miniconda/envs/ae-p38/lib/python3.8/urllib/request.py", line 569, in error
            result = func(*args)download_url_to_file(url, cached_file, progress=False)
    
      File "/data/home/marijajegorova/miniconda/envs/ae-p38/lib/python3.8/urllib/request.py", line 755, in http_error_302
      File "/data/home/marijajegorova/miniconda/envs/ae-p38/lib/python3.8/site-packages/torch/hub.py", line 394, in download_url_to_file
        result = func(*args)
      File "/data/home/marijajegorova/miniconda/envs/ae-p38/lib/python3.8/urllib/request.py", line 755, in http_error_302
        return self._call_chain(*args)
      File "/data/home/marijajegorova/miniconda/envs/ae-p38/lib/python3.8/urllib/request.py", line 502, in _call_chain
        return self._call_chain(*args)
      File "/data/home/marijajegorova/miniconda/envs/ae-p38/lib/python3.8/urllib/request.py", line 502, in _call_chain
        return self.parent.open(new, timeout=req.timeout)
      File "/data/home/marijajegorova/miniconda/envs/ae-p38/lib/python3.8/urllib/request.py", line 531, in open
        u = urlopen(req)
      File "/data/home/marijajegorova/miniconda/envs/ae-p38/lib/python3.8/urllib/request.py", line 222, in urlopen
        return self.parent.open(new, timeout=req.timeout)
      File "/data/home/marijajegorova/miniconda/envs/ae-p38/lib/python3.8/urllib/request.py", line 531, in open
        result = func(*args)
      File "/data/home/marijajegorova/miniconda/envs/ae-p38/lib/python3.8/urllib/request.py", line 649, in http_error_default
        return opener.open(url, data, timeout)
      File "/data/home/marijajegorova/miniconda/envs/ae-p38/lib/python3.8/urllib/request.py", line 531, in open
        result = func(*args)
      File "/data/home/marijajegorova/miniconda/envs/ae-p38/lib/python3.8/urllib/request.py", line 649, in http_error_default
        response = meth(req, response)
      File "/data/home/marijajegorova/miniconda/envs/ae-p38/lib/python3.8/urllib/request.py", line 640, in http_response
        response = meth(req, response)
      File "/data/home/marijajegorova/miniconda/envs/ae-p38/lib/python3.8/urllib/request.py", line 640, in http_response
        raise HTTPError(req.full_url, code, msg, hdrs, fp)
    urllib.error.HTTPError: HTTP Error 404: Not Found
        response = meth(req, response)
      File "/data/home/marijajegorova/miniconda/envs/ae-p38/lib/python3.8/urllib/request.py", line 640, in http_response
        raise HTTPError(req.full_url, code, msg, hdrs, fp)
    urllib.error.HTTPError: HTTP Error 404: Not Found
        response = self.parent.error(
      File "/data/home/marijajegorova/miniconda/envs/ae-p38/lib/python3.8/urllib/request.py", line 569, in error
        response = self.parent.error(
      File "/data/home/marijajegorova/miniconda/envs/ae-p38/lib/python3.8/urllib/request.py", line 569, in error
        response = self.parent.error(
      File "/data/home/marijajegorova/miniconda/envs/ae-p38/lib/python3.8/urllib/request.py", line 563, in error
        return self._call_chain(*args)
      File "/data/home/marijajegorova/miniconda/envs/ae-p38/lib/python3.8/urllib/request.py", line 502, in _call_chain
        return self._call_chain(*args)
      File "/data/home/marijajegorova/miniconda/envs/ae-p38/lib/python3.8/urllib/request.py", line 502, in _call_chain
        result = func(*args)
      File "/data/home/marijajegorova/miniconda/envs/ae-p38/lib/python3.8/urllib/request.py", line 649, in http_error_default
        result = self._call_chain(*args)
      File "/data/home/marijajegorova/miniconda/envs/ae-p38/lib/python3.8/urllib/request.py", line 502, in _call_chain
        result = func(*args)
      File "/data/home/marijajegorova/miniconda/envs/ae-p38/lib/python3.8/urllib/request.py", line 649, in http_error_default
        raise HTTPError(req.full_url, code, msg, hdrs, fp)
    urllib.error.HTTPError: HTTP Error 404: Not Found
        result = func(*args)
      File "/data/home/marijajegorova/miniconda/envs/ae-p38/lib/python3.8/urllib/request.py", line 755, in http_error_302
        raise HTTPError(req.full_url, code, msg, hdrs, fp)
    urllib.error.HTTPError: HTTP Error 404: Not Found
        return self.parent.open(new, timeout=req.timeout)
      File "/data/home/marijajegorova/miniconda/envs/ae-p38/lib/python3.8/urllib/request.py", line 531, in open
        response = meth(req, response)
      File "/data/home/marijajegorova/miniconda/envs/ae-p38/lib/python3.8/urllib/request.py", line 640, in http_response
        response = self.parent.error(
      File "/data/home/marijajegorova/miniconda/envs/ae-p38/lib/python3.8/urllib/request.py", line 569, in error
        return self._call_chain(*args)
      File "/data/home/marijajegorova/miniconda/envs/ae-p38/lib/python3.8/urllib/request.py", line 502, in _call_chain
        result = func(*args)
      File "/data/home/marijajegorova/miniconda/envs/ae-p38/lib/python3.8/urllib/request.py", line 649, in http_error_default
        raise HTTPError(req.full_url, code, msg, hdrs, fp)
    urllib.error.HTTPError: HTTP Error 404: Not Found
        + torchvision_archs + torch.hub.list("facebookresearch/xcit"),
      File "/data/home/marijajegorova/miniconda/envs/ae-p38/lib/python3.8/site-packages/torch/hub.py", line 238, in list
        repo_dir = _get_cache_or_reload(github, force_reload, True)
      File "/data/home/marijajegorova/miniconda/envs/ae-p38/lib/python3.8/site-packages/torch/hub.py", line 144, in _get_cache_or_reload
        download_url_to_file(url, cached_file, progress=False)
      File "/data/home/marijajegorova/miniconda/envs/ae-p38/lib/python3.8/site-packages/torch/hub.py", line 394, in download_url_to_file
        u = urlopen(req)
      File "/data/home/marijajegorova/miniconda/envs/ae-p38/lib/python3.8/urllib/request.py", line 222, in urlopen
        return opener.open(url, data, timeout)
      File "/data/home/marijajegorova/miniconda/envs/ae-p38/lib/python3.8/urllib/request.py", line 531, in open
        response = meth(req, response)
      File "/data/home/marijajegorova/miniconda/envs/ae-p38/lib/python3.8/urllib/request.py", line 640, in http_response
        response = self.parent.error(
      File "/data/home/marijajegorova/miniconda/envs/ae-p38/lib/python3.8/urllib/request.py", line 563, in error
        result = self._call_chain(*args)
      File "/data/home/marijajegorova/miniconda/envs/ae-p38/lib/python3.8/urllib/request.py", line 502, in _call_chain
        result = func(*args)
      File "/data/home/marijajegorova/miniconda/envs/ae-p38/lib/python3.8/urllib/request.py", line 755, in http_error_302
        return self.parent.open(new, timeout=req.timeout)
      File "/data/home/marijajegorova/miniconda/envs/ae-p38/lib/python3.8/urllib/request.py", line 531, in open
        response = meth(req, response)
      File "/data/home/marijajegorova/miniconda/envs/ae-p38/lib/python3.8/urllib/request.py", line 640, in http_response
        response = self.parent.error(
      File "/data/home/marijajegorova/miniconda/envs/ae-p38/lib/python3.8/urllib/request.py", line 569, in error
        return self._call_chain(*args)
      File "/data/home/marijajegorova/miniconda/envs/ae-p38/lib/python3.8/urllib/request.py", line 502, in _call_chain
        result = func(*args)
      File "/data/home/marijajegorova/miniconda/envs/ae-p38/lib/python3.8/urllib/request.py", line 649, in http_error_default
        raise HTTPError(req.full_url, code, msg, hdrs, fp)
    urllib.error.HTTPError: HTTP Error 404: Not Found
        + torchvision_archs + torch.hub.list("facebookresearch/xcit"),
      File "/data/home/marijajegorova/miniconda/envs/ae-p38/lib/python3.8/site-packages/torch/hub.py", line 238, in list
        + torchvision_archs + torch.hub.list("facebookresearch/xcit"),
      File "/data/home/marijajegorova/miniconda/envs/ae-p38/lib/python3.8/site-packages/torch/hub.py", line 238, in list
        repo_dir = _get_cache_or_reload(github, force_reload, True)
      File "/data/home/marijajegorova/miniconda/envs/ae-p38/lib/python3.8/site-packages/torch/hub.py", line 144, in _get_cache_or_reload
        download_url_to_file(url, cached_file, progress=False)
      File "/data/home/marijajegorova/miniconda/envs/ae-p38/lib/python3.8/site-packages/torch/hub.py", line 394, in download_url_to_file
        repo_dir = _get_cache_or_reload(github, force_reload, True)
      File "/data/home/marijajegorova/miniconda/envs/ae-p38/lib/python3.8/site-packages/torch/hub.py", line 144, in _get_cache_or_reload
        u = urlopen(req)
      File "/data/home/marijajegorova/miniconda/envs/ae-p38/lib/python3.8/urllib/request.py", line 222, in urlopen
        download_url_to_file(url, cached_file, progress=False)
      File "/data/home/marijajegorova/miniconda/envs/ae-p38/lib/python3.8/site-packages/torch/hub.py", line 394, in download_url_to_file
        return opener.open(url, data, timeout)
      File "/data/home/marijajegorova/miniconda/envs/ae-p38/lib/python3.8/urllib/request.py", line 531, in open
        u = urlopen(req)
      File "/data/home/marijajegorova/miniconda/envs/ae-p38/lib/python3.8/urllib/request.py", line 222, in urlopen
        response = meth(req, response)
      File "/data/home/marijajegorova/miniconda/envs/ae-p38/lib/python3.8/urllib/request.py", line 640, in http_response
        return opener.open(url, data, timeout)
      File "/data/home/marijajegorova/miniconda/envs/ae-p38/lib/python3.8/urllib/request.py", line 531, in open
        response = meth(req, response)
      File "/data/home/marijajegorova/miniconda/envs/ae-p38/lib/python3.8/urllib/request.py", line 640, in http_response
        response = self.parent.error(
      File "/data/home/marijajegorova/miniconda/envs/ae-p38/lib/python3.8/urllib/request.py", line 563, in error
        result = self._call_chain(*args)
      File "/data/home/marijajegorova/miniconda/envs/ae-p38/lib/python3.8/urllib/request.py", line 502, in _call_chain
        response = self.parent.error(
      File "/data/home/marijajegorova/miniconda/envs/ae-p38/lib/python3.8/urllib/request.py", line 563, in error
        result = self._call_chain(*args)
      File "/data/home/marijajegorova/miniconda/envs/ae-p38/lib/python3.8/urllib/request.py", line 502, in _call_chain
        result = func(*args)
      File "/data/home/marijajegorova/miniconda/envs/ae-p38/lib/python3.8/urllib/request.py", line 755, in http_error_302
        result = func(*args)
      File "/data/home/marijajegorova/miniconda/envs/ae-p38/lib/python3.8/urllib/request.py", line 755, in http_error_302
        return self.parent.open(new, timeout=req.timeout)
      File "/data/home/marijajegorova/miniconda/envs/ae-p38/lib/python3.8/urllib/request.py", line 531, in open
        return self.parent.open(new, timeout=req.timeout)
      File "/data/home/marijajegorova/miniconda/envs/ae-p38/lib/python3.8/urllib/request.py", line 531, in open
        response = meth(req, response)
      File "/data/home/marijajegorova/miniconda/envs/ae-p38/lib/python3.8/urllib/request.py", line 640, in http_response
        response = self.parent.error(
      File "/data/home/marijajegorova/miniconda/envs/ae-p38/lib/python3.8/urllib/request.py", line 569, in error
        response = meth(req, response)
      File "/data/home/marijajegorova/miniconda/envs/ae-p38/lib/python3.8/urllib/request.py", line 640, in http_response
        return self._call_chain(*args)
      File "/data/home/marijajegorova/miniconda/envs/ae-p38/lib/python3.8/urllib/request.py", line 502, in _call_chain
        response = self.parent.error(
      File "/data/home/marijajegorova/miniconda/envs/ae-p38/lib/python3.8/urllib/request.py", line 569, in error
        return self._call_chain(*args)
      File "/data/home/marijajegorova/miniconda/envs/ae-p38/lib/python3.8/urllib/request.py", line 502, in _call_chain
        result = func(*args)
      File "/data/home/marijajegorova/miniconda/envs/ae-p38/lib/python3.8/urllib/request.py", line 649, in http_error_default
        raise HTTPError(req.full_url, code, msg, hdrs, fp)
    urllib.error.HTTPError: HTTP Error 404: Not Found
        result = func(*args)
      File "/data/home/marijajegorova/miniconda/envs/ae-p38/lib/python3.8/urllib/request.py", line 649, in http_error_default
        raise HTTPError(req.full_url, code, msg, hdrs, fp)
    urllib.error.HTTPError: HTTP Error 404: Not Found
    Killing subprocess 26135
    Killing subprocess 26136
    Killing subprocess 26137
    Killing subprocess 26138
    Killing subprocess 26139
    Killing subprocess 26140
    Killing subprocess 26141
    Killing subprocess 26142
    Traceback (most recent call last):
      File "/data/home/marijajegorova/miniconda/envs/ae-p38/lib/python3.8/runpy.py", line 194, in _run_module_as_main
        return _run_code(code, main_globals, None,
      File "/data/home/marijajegorova/miniconda/envs/ae-p38/lib/python3.8/runpy.py", line 87, in _run_code
        exec(code, run_globals)
      File "/data/home/marijajegorova/miniconda/envs/ae-p38/lib/python3.8/site-packages/torch/distributed/launch.py", line 340, in <module>
        main()
      File "/data/home/marijajegorova/miniconda/envs/ae-p38/lib/python3.8/site-packages/torch/distributed/launch.py", line 326, in main
        sigkill_handler(signal.SIGTERM, None)  # not coming back
      File "/data/home/marijajegorova/miniconda/envs/ae-p38/lib/python3.8/site-packages/torch/distributed/launch.py", line 301, in sigkill_handler
        raise subprocess.CalledProcessError(returncode=last_return_code, cmd=cmd)
    subprocess.CalledProcessError: Command '['/data/home/marijajegorova/miniconda/envs/ae-p38/bin/python', '-u', 'main_dino.py', '--local_rank=7', '--arch', 'vit_small', '--data_path', '../pre-process/step2_affine_transformation/LRS3_fullface13_correct_mp4', '--output_dir', '/LRS3_dino_pretext/']' returned non-zero exit status 1.

**Comment by woctezuma** [comment]
Apparently, the program tries to download this file:
`https://github.com/facebookresearch/xcit/archive/master.zip`
and returns:
`HTTP Error 404: Not Found`

You can try to access [the URL]: it redirects to:
`https://codeload.github.com/facebookresearch/xcit/zip/master`
and it indeed fails.

**Comment by Instassa** [comment]
@woctezuma You were right, it was at least partially connected - I have pulled the more recent version with a main.py fix.

Now I get a different set of errors:

    *****************************************
    Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
    *****************************************
    Downloading: "https://github.com/facebookresearch/xcit/archive/main.zip" to /data/home/marijajegorova/.cache/torch/hub/main.zip
    Traceback (most recent call last):
      File "main_dino.py", line 468, in <module>
    Traceback (most recent call last):
    Traceback (most recent call last):
      File "main_dino.py", line 468, in <module>
      File "main_dino.py", line 468, in <module>
    Traceback (most recent call last):
    Traceback (most recent call last):
      File "main_dino.py", line 468, in <module>
      File "main_dino.py", line 468, in <module>
    Traceback (most recent call last):
      File "main_dino.py", line 468, in <module>
    Traceback (most recent call last):
      File "main_dino.py", line 468, in <module>
        parser = argparse.ArgumentParser('DINO', parents=[get_args_parser()])
      File "main_dino.py", line 47, in get_args_parser
        parser = argparse.ArgumentParser('DINO', parents=[get_args_parser()])
        parser = argparse.ArgumentParser('DINO', parents=[get_args_parser()])            
    parser = argparse.ArgumentParser('DINO', parents=[get_args_parser()])parser = argparse.ArgumentParser('DINO', parents=[get_args_parser()])+ torchvision_archs + torch.hub.list("facebookresearch/xcit:main"),  File "main_dino.py", line 47, in get_args_parser
        
    
    
    parser = argparse.ArgumentParser('DINO', parents=[get_args_parser()])  File "main_dino.py", line 47, in get_args_parser
      File "main_dino.py", line 47, in get_args_parser
    
      File "main_dino.py", line 47, in get_args_parser
      File "/data/home/marijajegorova/miniconda/envs/ae-p38/lib/python3.8/site-packages/torch/hub.py", line 238, in list
        + torchvision_archs + torch.hub.list("facebookresearch/xcit:main"),
      File "/data/home/marijajegorova/miniconda/envs/ae-p38/lib/python3.8/site-packages/torch/hub.py", line 238, in list
      File "main_dino.py", line 47, in get_args_parser
        + torchvision_archs + torch.hub.list("facebookresearch/xcit:main"),
      File "/data/home/marijajegorova/miniconda/envs/ae-p38/lib/python3.8/site-packages/torch/hub.py", line 238, in list
        + torchvision_archs + torch.hub.list("facebookresearch/xcit:main"),
      File "/data/home/marijajegorova/miniconda/envs/ae-p38/lib/python3.8/site-packages/torch/hub.py", line 238, in list
        parser = argparse.ArgumentParser('DINO', parents=[get_args_parser()])
      File "main_dino.py", line 47, in get_args_parser
        + torchvision_archs + torch.hub.list("facebookresearch/xcit:main"),
      File "/data/home/marijajegorova/miniconda/envs/ae-p38/lib/python3.8/site-packages/torch/hub.py", line 238, in list
        repo_dir = _get_cache_or_reload(github, force_reload, True)
      File "/data/home/marijajegorova/miniconda/envs/ae-p38/lib/python3.8/site-packages/torch/hub.py", line 140, in _get_cache_or_reload
        repo_dir = _get_cache_or_reload(github, force_reload, True)
      File "/data/home/marijajegorova/miniconda/envs/ae-p38/lib/python3.8/site-packages/torch/hub.py", line 140, in _get_cache_or_reload
        repo_dir = _get_cache_or_reload(github, force_reload, True)    
    repo_dir = _get_cache_or_reload(github, force_reload, True)  File "/data/home/marijajegorova/miniconda/envs/ae-p38/lib/python3.8/site-packages/torch/hub.py", line 140, in _get_cache_or_reload
    
      File "/data/home/marijajegorova/miniconda/envs/ae-p38/lib/python3.8/site-packages/torch/hub.py", line 140, in _get_cache_or_reload
        repo_dir = _get_cache_or_reload(github, force_reload, True)
      File "/data/home/marijajegorova/miniconda/envs/ae-p38/lib/python3.8/site-packages/torch/hub.py", line 140, in _get_cache_or_reload
        _remove_if_exists(cached_file)
      File "/data/home/marijajegorova/miniconda/envs/ae-p38/lib/python3.8/site-packages/torch/hub.py", line 81, in _remove_if_exists
        _remove_if_exists(cached_file)
      File "/data/home/marijajegorova/miniconda/envs/ae-p38/lib/python3.8/site-packages/torch/hub.py", line 81, in _remove_if_exists
        _remove_if_exists(cached_file)
      File "/data/home/marijajegorova/miniconda/envs/ae-p38/lib/python3.8/site-packages/torch/hub.py", line 81, in _remove_if_exists
        _remove_if_exists(cached_file)
      File "/data/home/marijajegorova/miniconda/envs/ae-p38/lib/python3.8/site-packages/torch/hub.py", line 81, in _remove_if_exists
        _remove_if_exists(cached_file)
      File "/data/home/marijajegorova/miniconda/envs/ae-p38/lib/python3.8/site-packages/torch/hub.py", line 81, in _remove_if_exists
        os.remove(path)
    FileNotFoundError: [Errno 2] No such file or directory: '/data/home/marijajegorova/.cache/torch/hub/main.zip'
        os.remove(path)
    FileNotFoundError: [Errno 2] No such file or directory: '/data/home/marijajegorova/.cache/torch/hub/main.zip'
        os.remove(path)
    FileNotFoundError: [Errno 2] No such file or directory: '/data/home/marijajegorova/.cache/torch/hub/main.zip'
            os.remove(path)os.remove(path)
    
    FileNotFoundErrorFileNotFoundError: [Errno 2] No such file or directory: '/data/home/marijajegorova/.cache/torch/hub/main.zip': 
    [Errno 2] No such file or directory: '/data/home/marijajegorova/.cache/torch/hub/main.zip'
        + torchvision_archs + torch.hub.list("facebookresearch/xcit:main"),
      File "/data/home/marijajegorova/miniconda/envs/ae-p38/lib/python3.8/site-packages/torch/hub.py", line 238, in list
        + torchvision_archs + torch.hub.list("facebookresearch/xcit:main"),
      File "/data/home/marijajegorova/miniconda/envs/ae-p38/lib/python3.8/site-packages/torch/hub.py", line 238, in list
        repo_dir = _get_cache_or_reload(github, force_reload, True)
      File "/data/home/marijajegorova/miniconda/envs/ae-p38/lib/python3.8/site-packages/torch/hub.py", line 140, in _get_cache_or_reload
        repo_dir = _get_cache_or_reload(github, force_reload, True)
      File "/data/home/marijajegorova/miniconda/envs/ae-p38/lib/python3.8/site-packages/torch/hub.py", line 140, in _get_cache_or_reload
        _remove_if_exists(cached_file)
      File "/data/home/marijajegorova/miniconda/envs/ae-p38/lib/python3.8/site-packages/torch/hub.py", line 81, in _remove_if_exists
        _remove_if_exists(cached_file)
      File "/data/home/marijajegorova/miniconda/envs/ae-p38/lib/python3.8/site-packages/torch/hub.py", line 81, in _remove_if_exists
        os.remove(path)
    FileNotFoundError: [Errno 2] No such file or directory: '/data/home/marijajegorova/.cache/torch/hub/main.zip'
        os.remove(path)
    FileNotFoundError: [Errno 2] No such file or directory: '/data/home/marijajegorova/.cache/torch/hub/main.zip'
    Killing subprocess 76621
    Killing subprocess 76622
    Killing subprocess 76623
    Killing subprocess 76624
    Killing subprocess 76625
    Killing subprocess 76626
    Killing subprocess 76627
    Killing subprocess 76628
    Traceback (most recent call last):
      File "/data/home/marijajegorova/miniconda/envs/ae-p38/lib/python3.8/runpy.py", line 194, in _run_module_as_main
        return _run_code(code, main_globals, None,
      File "/data/home/marijajegorova/miniconda/envs/ae-p38/lib/python3.8/runpy.py", line 87, in _run_code
        exec(code, run_globals)
      File "/data/home/marijajegorova/miniconda/envs/ae-p38/lib/python3.8/site-packages/torch/distributed/launch.py", line 340, in <module>
        main()
      File "/data/home/marijajegorova/miniconda/envs/ae-p38/lib/python3.8/site-packages/torch/distributed/launch.py", line 326, in main
        sigkill_handler(signal.SIGTERM, None)  # not coming back
      File "/data/home/marijajegorova/miniconda/envs/ae-p38/lib/python3.8/site-packages/torch/distributed/launch.py", line 301, in sigkill_handler
        raise subprocess.CalledProcessError(returncode=last_return_code, cmd=cmd)
    subprocess.CalledProcessError: Command '['/data/home/marijajegorova/miniconda/envs/ae-p38/bin/python', '-u', 'main_dino.py', '--local_rank=7', '--arch', 'vit_small', '--data_path', '../pre-process/step2_affine_transformation/LRS3_fullface13_correct_mp4', '--output_dir', '/LRS3_dino_pretext/']' returned non-zero exit status 1.
