### ISSUE TITLE
Out of Memory when running eval_knn.py

### ISSUE THREAD

**Issue by Lost2Dream** [facebookresearch/dino#161]
When I using pre-trained weights to evaluate knn
```
Traceback (most recent call last):
  File "../main/eval_knn.py", line 234, in <module>
    train_features, test_features, train_labels, test_labels = extract_feature_pipeline(args)
  File "../main/eval_knn.py", line 82, in extract_feature_pipeline
    train_features = nn.functional.normalize(train_features, dim=1, p=2)
  File "/root/anaconda3/envs/DINO/lib/python3.7/site-packages/torch/nn/functional.py", line 3591, in normalize
    return input / denom
RuntimeError: NPU out of memory. Tried to allocate 9.78 GiB (NPU 0; 32.00 GiB total capacity; 29.80 GiB already allocated; 1.59 GiB free; 50.34 MiB cached)
```
And the NPU(GPU) is 32GB, how can I solve it?

appreciate a lot!

**Comment by Lost2Dream** [comment]
btw, I set batch size to 16

**Comment by DoganK01** [comment]
Hey, where is the batch size ? I couldnt find it

**Comment by DoganK01** [comment]
Okay found it :D

**Comment by DoganK01** [comment]
Hey, how did u solve that ? I was tryin it on colab gpu but got same error
