### ISSUE TITLE
NameError: name 'max_accuracy' is not defined

### ISSUE THREAD

**Issue by user1234554321** [facebookresearch/dino#17]
I have tried to run the eval_linear.py after training dino on a custom dataset. I get the folowing error:
`
Traceback (most recent call last):
  File "/home/ubuntu/dino/eval_linear.py", line 250, in <module>
    eval_linear(args)
  File "/home/ubuntu/dino/eval_linear.py", line 142, in eval_linear
    "Top-1 test accuracy: {acc:.1f}".format(acc=max_accuracy))
NameError: name 'max_accuracy' is not defined
Killing subprocess 44659
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/pytorch/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/ubuntu/anaconda3/envs/pytorch/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/anaconda3/envs/pytorch/lib/python3.9/site-packages/torch/distributed/launch.py", line 340, in <module>
    main()
  File "/home/ubuntu/anaconda3/envs/pytorch/lib/python3.9/site-packages/torch/distributed/launch.py", line 326, in main
    sigkill_handler(signal.SIGTERM, None)  # not coming back
  File "/home/ubuntu/anaconda3/envs/pytorch/lib/python3.9/site-packages/torch/distributed/launch.py", line 301, in sigkill_handler
    raise subprocess.CalledProcessError(returncode=last_return_code, cmd=cmd)
subprocess.CalledProcessError: Command '['/home/ubuntu/anaconda3/envs/pytorch/bin/python', '-u', 'eval_linear.py', '--local_rank=0', '--data_path', 'images', '--pretrained_weights', 'runs/checkpoint.pth']' returned non-zero exit status 1.

`

After skimming through the lines above it, I believe it should be best_acc rather than max_accuracy ? 
Note: I have changed the dataset class (pytorch dataset) so as to work on my custom dataset but I believe the error still stands as I tried finding max_accuracy in the entire file and found only one occurrence (i.e., not defined earlier).

**Comment by woctezuma** [comment]
True.

https://github.com/facebookresearch/dino/blob/8aa93fdc90eae4b183c4e3c005174a9f634ecfbf/eval_linear.py#L114-L115

vs.

https://github.com/facebookresearch/dino/blob/8aa93fdc90eae4b183c4e3c005174a9f634ecfbf/eval_linear.py#L98-L100

**Comment by mathildecaron31** [comment]
Thanks, I have merged the PR.
