### ISSUE TITLE
Inconsistency in defaults?

### ISSUE THREAD

**Issue by ketil-malde** [facebookresearch/dino#176]
I trained dino with default settings (the `vit_small` arch), and tried to run the `video_generation.py` script to look at the results.  This gave the following error:

```
Take key teacher in provided checkpoint dict
Traceback (most recent call last):
  File "/usr/src/app/video_generation.py", line 377, in <module>
    vg = VideoGenerator(args)
  File "/usr/src/app/video_generation.py", line 46, in __init__
    self.model = self.__load_model()
  File "/usr/src/app/video_generation.py", line 263, in __load_model
    msg = model.load_state_dict(state_dict, strict=False)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1070, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for VisionTransformer:
        size mismatch for pos_embed: copying a param with shape torch.Size([1, 197, 384]) from checkpoint, the shape in current model is torch.Size([1, 785, 384]).
        size mismatch for patch_embed.proj.weight: copying a param with shape torch.Size([384, 3, 16, 16]) from checkpoint, the shape in current model is torch.Size([384, 3, 8, 8]).
```
I think this is caused by training defaulting to patch_size of 16, while video generation defaults to 8.  Adding `--patch_size 16` to the video_generation command line seems to have fixed it.

(No big deal, of course, but thought I might as well report it.)

**Comment by ketil-malde** [comment]
I think it's just a matter of changing line 307 in `video_generation.py` from:
```
"--patch_size", default=8, type=int, help="Patch resolution of the self.model."
```
to
```
"--patch_size", default=16, type=int, help="Patch resolution of the self.model."
```

(Or, alternatively, change the default to 8 in `main_dino.py`)

**Comment by woctezuma** [comment]
True.

https://github.com/facebookresearch/dino/blob/cb711401860da580817918b9167ed73e3eef3dcf/main_dino.py#L50-L54

https://github.com/facebookresearch/dino/blob/94175993abde84179449d79e22eab7ea28dec14b/visualize_attention.py#L102

**Comment by mathildecaron31** [comment]
Thanks @ketil-malde 
However having left Meta I no longer can accept pull request.

**Comment by ketil-malde** [comment]
If Dino is no longer maintained by FB, perhaps we should set up a semi-official fork?  If you or anybody else is interested, contact me at ketil (at) malde (dot) org, and we can discuss the details.
