### ISSUE TITLE
Out of Memory when running video_generation.py

### ISSUE THREAD

**Issue by DoganK01** [facebookresearch/dino#213]
Traceback (most recent call last):
  File "video_generation.py", line 378, in <module>
    vg.run()
  File "video_generation.py", line 76, in run
    attention_folder,
  File "video_generation.py", line 190, in _inference
    attentions = self.model.get_last_selfattention(img.to(DEVICE))
  File "/content/gdrive/MyDrive/dino/vision_transformer.py", line 220, in get_last_selfattention
    x = blk(x)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/content/gdrive/MyDrive/dino/vision_transformer.py", line 108, in forward
    y, attn = self.attn(self.norm1(x))
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/content/gdrive/MyDrive/dino/vision_transformer.py", line 85, in forward
    attn = (q @ k.transpose(-2, -1)) * self.scale
RuntimeError: CUDA out of memory. Tried to allocate 4.64 GiB (GPU 0; 14.76 GiB total capacity; 4.83 GiB already allocated; 4.24 GiB free; 9.46 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by DoganK01** [comment]
and I set batch size to 16 and then 8
