### ISSUE TITLE
sock.connect(sa)TimeoutError  : raise err[Errno 110] Connection timed out

### ISSUE THREAD

**Issue by wdc233** [facebookresearch/dino#233]
I keep making these errors, but the Internet connection is fine
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
Downloading: "https://github.com/facebookresearch/xcit/archive/main.zip" to /home/wendongcheng/.cache/torch/hub/main.zip
Downloading: "https://github.com/facebookresearch/xcit/archive/main.zip" to /home/wendongcheng/.cache/torch/hub/main.zip
Downloading: "https://github.com/facebookresearch/xcit/archive/main.zip" to /home/wendongcheng/.cache/torch/hub/main.zip
Downloading: "https://github.com/facebookresearch/xcit/archive/main.zip" to /home/wendongcheng/.cache/torch/hub/main.zip
Downloading: "https://github.com/facebookresearch/xcit/archive/main.zip" to /home/wendongcheng/.cache/torch/hub/main.zip
Downloading: "https://github.com/facebookresearch/xcit/archive/main.zip" to /home/wendongcheng/.cache/torch/hub/main.zip
Downloading: "https://github.com/facebookresearch/xcit/archive/main.zip" to /home/wendongcheng/.cache/torch/hub/main.zip
Downloading: "https://github.com/facebookresearch/xcit/archive/main.zip" to /home/wendongcheng/.cache/torch/hub/main.zip
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
  File "/home/wendongcheng/anaconda3/envs/pytorch/lib/python3.8/urllib/request.py", line 1354, in do_open
  File "/home/wendongcheng/anaconda3/envs/pytorch/lib/python3.8/urllib/request.py", line 1354, in do_open
  File "/home/wendongcheng/anaconda3/envs/pytorch/lib/python3.8/urllib/request.py", line 1354, in do_open
  File "/home/wendongcheng/anaconda3/envs/pytorch/lib/python3.8/urllib/request.py", line 1354, in do_open
  File "/home/wendongcheng/anaconda3/envs/pytorch/lib/python3.8/urllib/request.py", line 1354, in do_open
Traceback (most recent call last):
Traceback (most recent call last):
  File "/home/wendongcheng/anaconda3/envs/pytorch/lib/python3.8/urllib/request.py", line 1354, in do_open
  File "/home/wendongcheng/anaconda3/envs/pytorch/lib/python3.8/urllib/request.py", line 1354, in do_open
  File "/home/wendongcheng/anaconda3/envs/pytorch/lib/python3.8/urllib/request.py", line 1354, in do_open
            h.request(req.get_method(), req.selector, req.data, headers,h.request(req.get_method(), req.selector, req.data, headers,h.request(req.get_method(), req.selector, req.data, headers,    

h.request(req.get_method(), req.selector, req.data, headers,  File "/home/wendongcheng/anaconda3/envs/pytorch/lib/python3.8/http/client.py", line 1256, in request
  File "/home/wendongcheng/anaconda3/envs/pytorch/lib/python3.8/http/client.py", line 1256, in request
  File "/home/wendongcheng/anaconda3/envs/pytorch/lib/python3.8/http/client.py", line 1256, in request

          File "/home/wendongcheng/anaconda3/envs/pytorch/lib/python3.8/http/client.py", line 1256, in request
h.request(req.get_method(), req.selector, req.data, headers,h.request(req.get_method(), req.selector, req.data, headers,

  File "/home/wendongcheng/anaconda3/envs/pytorch/lib/python3.8/http/client.py", line 1256, in request
  File "/home/wendongcheng/anaconda3/envs/pytorch/lib/python3.8/http/client.py", line 1256, in request
        self._send_request(method, url, body, headers, encode_chunked)self._send_request(method, url, body, headers, encode_chunked)    

self._send_request(method, url, body, headers, encode_chunked)      File "/home/wendongcheng/anaconda3/envs/pytorch/lib/python3.8/http/client.py", line 1302, in _send_request
  File "/home/wendongcheng/anaconda3/envs/pytorch/lib/python3.8/http/client.py", line 1302, in _send_request

self._send_request(method, url, body, headers, encode_chunked)
      File "/home/wendongcheng/anaconda3/envs/pytorch/lib/python3.8/http/client.py", line 1302, in _send_request
    self._send_request(method, url, body, headers, encode_chunked)  File "/home/wendongcheng/anaconda3/envs/pytorch/lib/python3.8/http/client.py", line 1302, in _send_request
self._send_request(method, url, body, headers, encode_chunked)
        
  File "/home/wendongcheng/anaconda3/envs/pytorch/lib/python3.8/http/client.py", line 1302, in _send_request
h.request(req.get_method(), req.selector, req.data, headers,h.request(req.get_method(), req.selector, req.data, headers,  File "/home/wendongcheng/anaconda3/envs/pytorch/lib/python3.8/http/client.py", line 1302, in _send_request

  File "/home/wendongcheng/anaconda3/envs/pytorch/lib/python3.8/http/client.py", line 1256, in request
  File "/home/wendongcheng/anaconda3/envs/pytorch/lib/python3.8/http/client.py", line 1256, in request
    self.endheaders(body, encode_chunked=encode_chunked)
    self.endheaders(body, encode_chunked=encode_chunked)  File "/home/wendongcheng/anaconda3/envs/pytorch/lib/python3.8/http/client.py", line 1251, in endheaders

  File "/home/wendongcheng/anaconda3/envs/pytorch/lib/python3.8/http/client.py", line 1251, in endheaders
    self.endheaders(body, encode_chunked=encode_chunked)
      File "/home/wendongcheng/anaconda3/envs/pytorch/lib/python3.8/http/client.py", line 1251, in endheaders
self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/wendongcheng/anaconda3/envs/pytorch/lib/python3.8/http/client.py", line 1251, in endheaders
        self.endheaders(body, encode_chunked=encode_chunked)self.endheaders(body, encode_chunked=encode_chunked)

  File "/home/wendongcheng/anaconda3/envs/pytorch/lib/python3.8/http/client.py", line 1251, in endheaders
  File "/home/wendongcheng/anaconda3/envs/pytorch/lib/python3.8/http/client.py", line 1251, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/wendongcheng/anaconda3/envs/pytorch/lib/python3.8/http/client.py", line 1011, in _send_output
        self._send_output(message_body, encode_chunked=encode_chunked)self._send_output(message_body, encode_chunked=encode_chunked)    

self._send_output(message_body, encode_chunked=encode_chunked)  File "/home/wendongcheng/anaconda3/envs/pytorch/lib/python3.8/http/client.py", line 1011, in _send_output
  File "/home/wendongcheng/anaconda3/envs/pytorch/lib/python3.8/http/client.py", line 1011, in _send_output

  File "/home/wendongcheng/anaconda3/envs/pytorch/lib/python3.8/http/client.py", line 1011, in _send_output
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/wendongcheng/anaconda3/envs/pytorch/lib/python3.8/http/client.py", line 1011, in _send_output
        self._send_request(method, url, body, headers, encode_chunked)self._send_request(method, url, body, headers, encode_chunked)    

self._send_output(message_body, encode_chunked=encode_chunked)  File "/home/wendongcheng/anaconda3/envs/pytorch/lib/python3.8/http/client.py", line 1302, in _send_request

  File "/home/wendongcheng/anaconda3/envs/pytorch/lib/python3.8/http/client.py", line 1302, in _send_request
  File "/home/wendongcheng/anaconda3/envs/pytorch/lib/python3.8/http/client.py", line 1011, in _send_output
    self.send(msg)
  File "/home/wendongcheng/anaconda3/envs/pytorch/lib/python3.8/http/client.py", line 951, in send
        self.send(msg)self.send(msg)

  File "/home/wendongcheng/anaconda3/envs/pytorch/lib/python3.8/http/client.py", line 951, in send
      File "/home/wendongcheng/anaconda3/envs/pytorch/lib/python3.8/http/client.py", line 951, in send
self.send(msg)
  File "/home/wendongcheng/anaconda3/envs/pytorch/lib/python3.8/http/client.py", line 951, in send
    self.send(msg)
  File "/home/wendongcheng/anaconda3/envs/pytorch/lib/python3.8/http/client.py", line 951, in send
    self.send(msg)
  File "/home/wendongcheng/anaconda3/envs/pytorch/lib/python3.8/http/client.py", line 951, in send
    self.connect()
  File "/home/wendongcheng/anaconda3/envs/pytorch/lib/python3.8/http/client.py", line 1418, in connect
        self.connect()self.connect()

  File "/home/wendongcheng/anaconda3/envs/pytorch/lib/python3.8/http/client.py", line 1418, in connect
  File "/home/wendongcheng/anaconda3/envs/pytorch/lib/python3.8/http/client.py", line 1418, in connect
    self.connect()
  File "/home/wendongcheng/anaconda3/envs/pytorch/lib/python3.8/http/client.py", line 1418, in connect
    self.connect()
  File "/home/wendongcheng/anaconda3/envs/pytorch/lib/python3.8/http/client.py", line 1418, in connect
    self.connect()
  File "/home/wendongcheng/anaconda3/envs/pytorch/lib/python3.8/http/client.py", line 1418, in connect
        self.endheaders(body, encode_chunked=encode_chunked)self.endheaders(body, encode_chunked=encode_chunked)

  File "/home/wendongcheng/anaconda3/envs/pytorch/lib/python3.8/http/client.py", line 1251, in endheaders
  File "/home/wendongcheng/anaconda3/envs/pytorch/lib/python3.8/http/client.py", line 1251, in endheaders
    super().connect()
  File "/home/wendongcheng/anaconda3/envs/pytorch/lib/python3.8/http/client.py", line 922, in connect
        super().connect()super().connect()

  File "/home/wendongcheng/anaconda3/envs/pytorch/lib/python3.8/http/client.py", line 922, in connect
  File "/home/wendongcheng/anaconda3/envs/pytorch/lib/python3.8/http/client.py", line 922, in connect
    super().connect()
  File "/home/wendongcheng/anaconda3/envs/pytorch/lib/python3.8/http/client.py", line 922, in connect
    super().connect()
  File "/home/wendongcheng/anaconda3/envs/pytorch/lib/python3.8/http/client.py", line 922, in connect
    super().connect()
  File "/home/wendongcheng/anaconda3/envs/pytorch/lib/python3.8/http/client.py", line 922, in connect
    self.sock = self._create_connection(
  File "/home/wendongcheng/anaconda3/envs/pytorch/lib/python3.8/socket.py", line 808, in create_connection
        self.sock = self._create_connection(self.sock = self._create_connection(

  File "/home/wendongcheng/anaconda3/envs/pytorch/lib/python3.8/socket.py", line 808, in create_connection
  File "/home/wendongcheng/anaconda3/envs/pytorch/lib/python3.8/socket.py", line 808, in create_connection
    self.sock = self._create_connection(
  File "/home/wendongcheng/anaconda3/envs/pytorch/lib/python3.8/socket.py", line 808, in create_connection
    self.sock = self._create_connection(
  File "/home/wendongcheng/anaconda3/envs/pytorch/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/home/wendongcheng/anaconda3/envs/pytorch/lib/python3.8/socket.py", line 796, in create_connection
    self.sock = self._create_connection(
  File "/home/wendongcheng/anaconda3/envs/pytorch/lib/python3.8/socket.py", line 808, in create_connection
    raise err    
raise err  File "/home/wendongcheng/anaconda3/envs/pytorch/lib/python3.8/socket.py", line 796, in create_connection

  File "/home/wendongcheng/anaconda3/envs/pytorch/lib/python3.8/socket.py", line 796, in create_connection
        self._send_output(message_body, encode_chunked=encode_chunked)self._send_output(message_body, encode_chunked=encode_chunked)

  File "/home/wendongcheng/anaconda3/envs/pytorch/lib/python3.8/http/client.py", line 1011, in _send_output
  File "/home/wendongcheng/anaconda3/envs/pytorch/lib/python3.8/http/client.py", line 1011, in _send_output
    raise err
  File "/home/wendongcheng/anaconda3/envs/pytorch/lib/python3.8/socket.py", line 796, in create_connection
    raise err
  File "/home/wendongcheng/anaconda3/envs/pytorch/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
    sock.connect(sa)  File "main_dino.py", line 469, in <module>

    sock.connect(sa)TimeoutError    
: raise err[Errno 110] Connection timed out

TimeoutError
During handling of the above exception, another exception occurred:

  File "/home/wendongcheng/anaconda3/envs/pytorch/lib/python3.8/socket.py", line 796, in create_connection
: Traceback (most recent call last):
[Errno 110] Connection timed out
  File "main_dino.py", line 469, in <module>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main_dino.py", line 469, in <module>
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main_dino.py", line 469, in <module>
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main_dino.py", line 469, in <module>
    sock.connect(sa)    
parser = argparse.ArgumentParser('DINO', parents=[get_args_parser()])
TimeoutError  File "main_dino.py", line 48, in get_args_parser
: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
      File "main_dino.py", line 469, in <module>
parser = argparse.ArgumentParser('DINO', parents=[get_args_parser()])
  File "main_dino.py", line 48, in get_args_parser
    parser = argparse.ArgumentParser('DINO', parents=[get_args_parser()])
  File "main_dino.py", line 48, in get_args_parser
        self.send(msg)self.send(msg)

      File "/home/wendongcheng/anaconda3/envs/pytorch/lib/python3.8/http/client.py", line 951, in send
  File "/home/wendongcheng/anaconda3/envs/pytorch/lib/python3.8/http/client.py", line 951, in send
+ torchvision_archs + torch.hub.list("facebookresearch/xcit:main"),
  File "/home/wendongcheng/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/hub.py", line 269, in list
    parser = argparse.ArgumentParser('DINO', parents=[get_args_parser()])
  File "main_dino.py", line 48, in get_args_parser
    + torchvision_archs + torch.hub.list("facebookresearch/xcit:main"),
  File "/home/wendongcheng/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/hub.py", line 269, in list
    + torchvision_archs + torch.hub.list("facebookresearch/xcit:main"),
  File "/home/wendongcheng/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/hub.py", line 269, in list
        + torchvision_archs + torch.hub.list("facebookresearch/xcit:main"),parser = argparse.ArgumentParser('DINO', parents=[get_args_parser()])
    
  File "/home/wendongcheng/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/hub.py", line 269, in list
repo_dir = _get_cache_or_reload(github, force_reload, True)  File "main_dino.py", line 48, in get_args_parser

      File "/home/wendongcheng/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/hub.py", line 141, in _get_cache_or_reload
repo_dir = _get_cache_or_reload(github, force_reload, True)
  File "/home/wendongcheng/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/hub.py", line 141, in _get_cache_or_reload
    repo_dir = _get_cache_or_reload(github, force_reload, True)
  File "/home/wendongcheng/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/hub.py", line 141, in _get_cache_or_reload
    download_url_to_file(url, cached_file, progress=False)
    download_url_to_file(url, cached_file, progress=False)  File "/home/wendongcheng/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/hub.py", line 425, in download_url_to_file

          File "/home/wendongcheng/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/hub.py", line 425, in download_url_to_file
repo_dir = _get_cache_or_reload(github, force_reload, True)    + torchvision_archs + torch.hub.list("facebookresearch/xcit:main"),
download_url_to_file(url, cached_file, progress=False)
  File "/home/wendongcheng/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/hub.py", line 141, in _get_cache_or_reload

  File "/home/wendongcheng/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/hub.py", line 269, in list
      File "/home/wendongcheng/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/hub.py", line 425, in download_url_to_file
parser = argparse.ArgumentParser('DINO', parents=[get_args_parser()])
  File "main_dino.py", line 48, in get_args_parser
    download_url_to_file(url, cached_file, progress=False)
  File "/home/wendongcheng/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/hub.py", line 425, in download_url_to_file
    u = urlopen(req)
    u = urlopen(req)  File "/home/wendongcheng/anaconda3/envs/pytorch/lib/python3.8/urllib/request.py", line 222, in urlopen

      File "/home/wendongcheng/anaconda3/envs/pytorch/lib/python3.8/urllib/request.py", line 222, in urlopen
repo_dir = _get_cache_or_reload(github, force_reload, True)
  File "/home/wendongcheng/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/hub.py", line 141, in _get_cache_or_reload
        + torchvision_archs + torch.hub.list("facebookresearch/xcit:main"),u = urlopen(req)

  File "/home/wendongcheng/anaconda3/envs/pytorch/lib/python3.8/urllib/request.py", line 222, in urlopen
  File "/home/wendongcheng/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/hub.py", line 269, in list
    u = urlopen(req)
      File "/home/wendongcheng/anaconda3/envs/pytorch/lib/python3.8/urllib/request.py", line 222, in urlopen
download_url_to_file(url, cached_file, progress=False)
  File "/home/wendongcheng/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/hub.py", line 425, in download_url_to_file
    return opener.open(url, data, timeout)
      File "/home/wendongcheng/anaconda3/envs/pytorch/lib/python3.8/urllib/request.py", line 525, in open
return opener.open(url, data, timeout)
  File "/home/wendongcheng/anaconda3/envs/pytorch/lib/python3.8/urllib/request.py", line 525, in open
    return opener.open(url, data, timeout)    
repo_dir = _get_cache_or_reload(github, force_reload, True)  File "/home/wendongcheng/anaconda3/envs/pytorch/lib/python3.8/urllib/request.py", line 525, in open
    
    self.connect()  File "/home/wendongcheng/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/hub.py", line 141, in _get_cache_or_reload
self.connect()

  File "/home/wendongcheng/anaconda3/envs/pytorch/lib/python3.8/http/client.py", line 1418, in connect
  File "/home/wendongcheng/anaconda3/envs/pytorch/lib/python3.8/http/client.py", line 1418, in connect
    return opener.open(url, data, timeout)
  File "/home/wendongcheng/anaconda3/envs/pytorch/lib/python3.8/urllib/request.py", line 525, in open
    u = urlopen(req)
  File "/home/wendongcheng/anaconda3/envs/pytorch/lib/python3.8/urllib/request.py", line 222, in urlopen
    download_url_to_file(url, cached_file, progress=False)
  File "/home/wendongcheng/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/hub.py", line 425, in download_url_to_file
    response = self._open(req, data)
      File "/home/wendongcheng/anaconda3/envs/pytorch/lib/python3.8/urllib/request.py", line 542, in _open
response = self._open(req, data)
  File "/home/wendongcheng/anaconda3/envs/pytorch/lib/python3.8/urllib/request.py", line 542, in _open
    response = self._open(req, data)
  File "/home/wendongcheng/anaconda3/envs/pytorch/lib/python3.8/urllib/request.py", line 542, in _open
    return opener.open(url, data, timeout)
  File "/home/wendongcheng/anaconda3/envs/pytorch/lib/python3.8/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/home/wendongcheng/anaconda3/envs/pytorch/lib/python3.8/urllib/request.py", line 542, in _open
    u = urlopen(req)
  File "/home/wendongcheng/anaconda3/envs/pytorch/lib/python3.8/urllib/request.py", line 222, in urlopen
    result = self._call_chain(self.handle_open, protocol, protocol +
      File "/home/wendongcheng/anaconda3/envs/pytorch/lib/python3.8/urllib/request.py", line 502, in _call_chain
result = self._call_chain(self.handle_open, protocol, protocol +
  File "/home/wendongcheng/anaconda3/envs/pytorch/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/home/wendongcheng/anaconda3/envs/pytorch/lib/python3.8/urllib/request.py", line 502, in _call_chain
    response = self._open(req, data)
  File "/home/wendongcheng/anaconda3/envs/pytorch/lib/python3.8/urllib/request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/home/wendongcheng/anaconda3/envs/pytorch/lib/python3.8/urllib/request.py", line 502, in _call_chain
    return opener.open(url, data, timeout)
  File "/home/wendongcheng/anaconda3/envs/pytorch/lib/python3.8/urllib/request.py", line 525, in open
    result = func(*args)
      File "/home/wendongcheng/anaconda3/envs/pytorch/lib/python3.8/urllib/request.py", line 1397, in https_open
result = func(*args)
  File "/home/wendongcheng/anaconda3/envs/pytorch/lib/python3.8/urllib/request.py", line 1397, in https_open
    result = func(*args)
  File "/home/wendongcheng/anaconda3/envs/pytorch/lib/python3.8/urllib/request.py", line 1397, in https_open
        result = self._call_chain(self.handle_open, protocol, protocol +result = func(*args)

  File "/home/wendongcheng/anaconda3/envs/pytorch/lib/python3.8/urllib/request.py", line 502, in _call_chain
  File "/home/wendongcheng/anaconda3/envs/pytorch/lib/python3.8/urllib/request.py", line 1397, in https_open
    response = self._open(req, data)
  File "/home/wendongcheng/anaconda3/envs/pytorch/lib/python3.8/urllib/request.py", line 542, in _open
        super().connect()super().connect()

    result = func(*args)  File "/home/wendongcheng/anaconda3/envs/pytorch/lib/python3.8/http/client.py", line 922, in connect
  File "/home/wendongcheng/anaconda3/envs/pytorch/lib/python3.8/http/client.py", line 922, in connect

  File "/home/wendongcheng/anaconda3/envs/pytorch/lib/python3.8/urllib/request.py", line 1397, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
      File "/home/wendongcheng/anaconda3/envs/pytorch/lib/python3.8/urllib/request.py", line 1357, in do_open
return self.do_open(http.client.HTTPSConnection, req,
  File "/home/wendongcheng/anaconda3/envs/pytorch/lib/python3.8/urllib/request.py", line 1357, in do_open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/home/wendongcheng/anaconda3/envs/pytorch/lib/python3.8/urllib/request.py", line 502, in _call_chain
    return self.do_open(http.client.HTTPSConnection, req,
  File "/home/wendongcheng/anaconda3/envs/pytorch/lib/python3.8/urllib/request.py", line 1357, in do_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/home/wendongcheng/anaconda3/envs/pytorch/lib/python3.8/urllib/request.py", line 1357, in do_open
    result = func(*args)
  File "/home/wendongcheng/anaconda3/envs/pytorch/lib/python3.8/urllib/request.py", line 1397, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/home/wendongcheng/anaconda3/envs/pytorch/lib/python3.8/urllib/request.py", line 1357, in do_open
    raise URLError(err)
    urllib.errorraise URLError(err).
URLErrorurllib.error.URLError: <urlopen error [Errno 110] Connection timed out>
: <urlopen error [Errno 110] Connection timed out>
    raise URLError(err)
urllib.error.URLError:     <urlopen error [Errno 110] Connection timed out>raise URLError(err)

urllib.error.URLError: <urlopen error [Errno 110] Connection timed out>
        self.sock = self._create_connection(self.sock = self._create_connection(

  File "/home/wendongcheng/anaconda3/envs/pytorch/lib/python3.8/socket.py", line 808, in create_connection
  File "/home/wendongcheng/anaconda3/envs/pytorch/lib/python3.8/socket.py", line 808, in create_connection
    raise URLError(err)
    urllib.errorreturn self.do_open(http.client.HTTPSConnection, req,.
URLError  File "/home/wendongcheng/anaconda3/envs/pytorch/lib/python3.8/urllib/request.py", line 1357, in do_open
: <urlopen error [Errno 110] Connection timed out>
        raise errraise err

  File "/home/wendongcheng/anaconda3/envs/pytorch/lib/python3.8/socket.py", line 796, in create_connection
  File "/home/wendongcheng/anaconda3/envs/pytorch/lib/python3.8/socket.py", line 796, in create_connection
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 110] Connection timed out>
        sock.connect(sa)sock.connect(sa)

TimeoutErrorTimeoutError: [Errno 110] Connection timed out: 
[Errno 110] Connection timed out
During handling of the above exception, another exception occurred:

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
Traceback (most recent call last):
  File "main_dino.py", line 469, in <module>
  File "main_dino.py", line 469, in <module>
        parser = argparse.ArgumentParser('DINO', parents=[get_args_parser()])parser = argparse.ArgumentParser('DINO', parents=[get_args_parser()])

  File "main_dino.py", line 48, in get_args_parser
  File "main_dino.py", line 48, in get_args_parser
        + torchvision_archs + torch.hub.list("facebookresearch/xcit:main"),+ torchvision_archs + torch.hub.list("facebookresearch/xcit:main"),

  File "/home/wendongcheng/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/hub.py", line 269, in list
  File "/home/wendongcheng/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/hub.py", line 269, in list
        repo_dir = _get_cache_or_reload(github, force_reload, True)repo_dir = _get_cache_or_reload(github, force_reload, True)

  File "/home/wendongcheng/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/hub.py", line 141, in _get_cache_or_reload
  File "/home/wendongcheng/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/hub.py", line 141, in _get_cache_or_reload
        download_url_to_file(url, cached_file, progress=False)download_url_to_file(url, cached_file, progress=False)

  File "/home/wendongcheng/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/hub.py", line 425, in download_url_to_file
  File "/home/wendongcheng/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/hub.py", line 425, in download_url_to_file
        u = urlopen(req)u = urlopen(req)

  File "/home/wendongcheng/anaconda3/envs/pytorch/lib/python3.8/urllib/request.py", line 222, in urlopen
  File "/home/wendongcheng/anaconda3/envs/pytorch/lib/python3.8/urllib/request.py", line 222, in urlopen
        return opener.open(url, data, timeout)return opener.open(url, data, timeout)

  File "/home/wendongcheng/anaconda3/envs/pytorch/lib/python3.8/urllib/request.py", line 525, in open
  File "/home/wendongcheng/anaconda3/envs/pytorch/lib/python3.8/urllib/request.py", line 525, in open
        response = self._open(req, data)response = self._open(req, data)

  File "/home/wendongcheng/anaconda3/envs/pytorch/lib/python3.8/urllib/request.py", line 542, in _open
  File "/home/wendongcheng/anaconda3/envs/pytorch/lib/python3.8/urllib/request.py", line 542, in _open
        result = self._call_chain(self.handle_open, protocol, protocol +result = self._call_chain(self.handle_open, protocol, protocol +

  File "/home/wendongcheng/anaconda3/envs/pytorch/lib/python3.8/urllib/request.py", line 502, in _call_chain
  File "/home/wendongcheng/anaconda3/envs/pytorch/lib/python3.8/urllib/request.py", line 502, in _call_chain
        result = func(*args)result = func(*args)

  File "/home/wendongcheng/anaconda3/envs/pytorch/lib/python3.8/urllib/request.py", line 1397, in https_open
  File "/home/wendongcheng/anaconda3/envs/pytorch/lib/python3.8/urllib/request.py", line 1397, in https_open
        return self.do_open(http.client.HTTPSConnection, req,return self.do_open(http.client.HTTPSConnection, req,

  File "/home/wendongcheng/anaconda3/envs/pytorch/lib/python3.8/urllib/request.py", line 1357, in do_open
  File "/home/wendongcheng/anaconda3/envs/pytorch/lib/python3.8/urllib/request.py", line 1357, in do_open
        raise URLError(err)raise URLError(err)

urllib.errorurllib.error..URLErrorURLError: : <urlopen error [Errno 110] Connection timed out><urlopen error [Errno 110] Connection timed out>

Traceback (most recent call last):
  File "/home/wendongcheng/anaconda3/envs/pytorch/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/wendongcheng/anaconda3/envs/pytorch/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/wendongcheng/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/distributed/launch.py", line 260, in <module>
    main()
  File "/home/wendongcheng/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/distributed/launch.py", line 255, in main
    raise subprocess.CalledProcessError(returncode=process.returncode,
subprocess.CalledProcessError: Command '['/home/wendongcheng/anaconda3/envs/pytorch/bin/python', '-u', 'main_dino.py', '--local_rank=7', '--arch', 'vit_small', '--data_path', '/path/to/imagenet/train', '--output_dir', '/path/to/saving_dir']' returned non-zero exit status 1.

**Comment by crisyume** [comment]
have you solved the problem? I meet a similar one.
