### ISSUE TITLE
How to add custom DistributedSampler?

### ISSUE THREAD

**Issue by saisubramani** [facebookresearch/dino#73]
Hi, I am trying to load the dateset from text file which contains the path of the images. I had over written the  Data loader of PyTorch
as mentioned below:

Code :

           
    class custom_loader(Dataset):     
        def __init__(self,filepath=None,transform=None):
            try:
                self.filepath = open(filepath,'r')
            except Exception as e:
                msg = "The Path is not availabel: {} and the error mesaage is : {}".format(filepath,e)
                print("Error_message : ",msg)
            self.transform = transform
            self.path = self.list_path(self.filepath.readlines())
        
        def list_path(self,paths):
            path = []
            for i in paths:
                path.append(i.replace("\n",""))
            return path
    
        def __len__(self,):
            return len(self.path)
    
        def __getitem__(self,idx):
            #if torch.is_tensor(idx):
            #    idx = idx.tolist()
            img_path = self.path[idx]
            image = io.imread(img_path)
            sample =image
    
            if self.transform:
                sample = self.transform(sample)
            return sample

I had  initialized DataAugmentationDINO Class for transform functions,as used in "main.py" ,when i try to use the DistributedSampler function i am getting error.

`  "Argument interpolation should be of type InterpolationMode instead of int. "
Traceback (most recent call last):
  File "custom_data_loader.py", line 155, in <module>
    sampler = DistributedSampler(dataset)
  File "/home/reorder/dino_facebook/pytorch_dino/lib/python3.6/site-packages/torch/utils/data/distributed.py", line 65, in __init__
    num_replicas = dist.get_world_size()
  File "/home/reorder/dino_facebook/pytorch_dino/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 711, in get_world_size
    return _get_group_size(group)
  File "/home/reorder/dino_facebook/pytorch_dino/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 263, in _get_group_size
    default_pg = _get_default_group()
  File "/home/reorder/dino_facebook/pytorch_dino/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 347, in _get_default_group
    raise RuntimeError("Default process group has not been initialized, "
RuntimeError: Default process group has not been initialized, please make sure to call init_process_group.`

I cant able to figure out please help me to solve this error
Thanks in advance!

**Comment by juanigp** [comment]
are you launching the scripts provided by the repo or your own? 
DistributedSampler(dataset) will use the rank and world_size from torch.distributed.get_rank() and torch.distributed.get_world_size() but according to your error the distributed package was not initialised (which is actually done in main_dino.py)

**Comment by mathildecaron31** [comment]
Have you been able to solve your issue @saisubramani ?

**Comment by mathildecaron31** [comment]
I am closing the issue for no activity. Feel free to re-open @saisubramani
